### ISSUE TITLE
Add support to install 3rd-party packages

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/syntax-test-action#12]
### Relational

In case a syntax embeds a 3rd-party syntax it might be required to install it to succeed related syntax tests.

### Request

Add a variable like `packages` to pass a list of repositories to clone packages from.

```yml
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          default_packages: ${{ matrix.default_packages }}
          packages:
            - https://github.com/danro/LESS-sublime
            - https://github.com/braver/SublimeSass
            - ...
```
